/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"
#include <pthread.h>
#include <stdbool.h>
#include <stdio.h>
#include <unistd.h>

#define MAX_CLIENTS 1024

int counter = 0;

bool choosing[MAX_CLIENTS] = { false };
int numbers[MAX_CLIENTS] = { 0 };

int *
get_number_1_svc(void *argp, struct svc_req *rqstp)
{
	static int result;

    if (counter >= MAX_CLIENTS)
        counter = 0;

	choosing[counter] = true;
    int max_n = 0;
    for (int i = 0; i < MAX_CLIENTS; ++i)
        if (numbers[i] > max_n)
            max_n = numbers[i];

    numbers[counter] = ++max_n;
    choosing[counter] = false;

	result = numbers[counter];

    ++counter;

    printf("Клиент получил номер %d\n", result);

	return &result;
}

double *
bakery_service_1_svc(struct REQUEST *argp, struct svc_req *rqstp)
{
	static double  result;
    int num = argp->number;

	for (int i = 0; i < MAX_CLIENTS; ++i) {
        if (i == num) continue;
        while (choosing[i])
            ;
        while (numbers[i] != 0 && (numbers[i] < numbers[num] || (numbers[i] == numbers[num] && i < num)))
            ;
    }

    switch (argp->operation)
    {
        case '+':
            result = argp->arg1 + argp->arg2;
            break;
        case '-':
            result = argp->arg1 - argp->arg2;
            break;
        case '*':
            result = argp->arg1 * argp->arg2;
            break;
        case '/':
            if(argp->arg2 != 0)
                result = argp->arg1 / argp->arg2;
            else {
                fprintf(stderr, "Ошибка: Деление на ноль от клиента с номером %d.\n", num);
                result = 0;
            }
            break;
        default:
            fprintf(stderr, "Неизвестная операция от клиента с номером %d.\n", num);
            result = 0;
            break;
    }
    printf("Клиент с номером %d: %.2f %c %.2f = %.2f\n", argp->number, argp->arg1, argp->operation, argp->arg2, result);

	return &result;
}
