/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"
#include <stdio.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

char get_op_char(char op) {
    switch(op) {
        case 0:
            return '+';
        case 1:
            return '-';
        case 2:
            return '*';
        case 3:
            return '/';
        default:
            return '?';
    }
}

void
bakery_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char *get_number_1_arg;
	double  *result_2;
	struct REQUEST  bakery_service_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, BAKERY_PROG, BAKERY_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	while (1)
	{
		sleep(rand() % 2 + 1);

		memset(&bakery_service_1_arg, 0, sizeof(bakery_service_1_arg));

		result_1 = get_number_1((void*)&get_number_1_arg, clnt);
		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		bakery_service_1_arg.number = *result_1;
		printf("Клиент получил номер: %d\n", bakery_service_1_arg.number);

		bakery_service_1_arg.operation = get_op_char(rand() % 4);
		bakery_service_1_arg.arg1 = rand() % 1000 + 1;
		bakery_service_1_arg.arg2 = rand() % 900 + 1;

		sleep(rand() % 1);
		result_2 = bakery_service_1(&bakery_service_1_arg, clnt);
		if (result_2 == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		printf("Клиент с номером %d: %.2f %c %.2f = %.2f\n", bakery_service_1_arg.number, bakery_service_1_arg.arg1, bakery_service_1_arg.operation, bakery_service_1_arg.arg2, *result_2);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	bakery_prog_1 (host);
	exit (0);
}
